export const ADD_NOTE = 'ADD_NOTE';
export const DELETE_NOTE = 'DELETE_NOTE';
export const SET_NOTE_VALUE = 'SET_NOTE_VALUE';
export const SET_NOTE_COLOR = 'SET_NOTE_COLOR';
export const SET_NOTE_TITLE = 'SET_NOTE_TITLE';

export const GET_NOTES_REQUEST = 'GET_NOTES_REQUEST';
export const GET_NOTES_SUCCESS = 'GET_NOTES_SUCCESS';
export const GET_NOTES_FAILURE = 'GET_NOTES_FAILURE';

export const ADD_NOTE_REQUEST = 'ADD_NOTE_REQUEST';
export const ADD_NOTE_SUCCESS = 'ADD_NOTE_SUCCESS';
export const ADD_NOTE_FAILURE = 'ADD_NOTE_FAILURE';

export const DELETE_NOTE_REQUEST = 'DELETE_NOTE_REQUEST';
export const DELETE_NOTE_SUCCESS = 'DELETE_NOTE_SUCCESS';
export const DELETE_NOTE_FAILURE = 'DELETE_NOTE_FAILURE';

export const SET_NOTE_TITLE_REQUEST = 'SET_NOTE_TITLE_REQUEST';
export const SET_NOTE_TITLE_SUCCESS = 'SET_NOTE_TITLE_SUCCESS';
export const SET_NOTE_TITLE_FAILURE = 'SET_NOTE_TITLE_FAILURE';

export const SET_NOTE_VALUE_REQUEST = 'SET_NOTE_VALUE_REQUEST';
export const SET_NOTE_VALUE_SUCCESS = 'SET_NOTE_VALUE_SUCCESS';
export const SET_NOTE_VALUE_FAILURE = 'SET_NOTE_VALUE_FAILURE';

export const SET_NOTE_COLOR_REQUEST = 'SET_NOTE_COLOR_REQUEST';
export const SET_NOTE_COLOR_SUCCESS = 'SET_NOTE_COLOR_SUCCESS';
export const SET_NOTE_COLOR_FAILURE = 'SET_NOTE_COLOR_FAILURE';

export const GET_EVENTS = 'GET_EVENTS';
export const SET_EVENT = 'SET_EVENT';
export const DELETE_EVENT = 'DELETE_EVENT';
export const PUT_EVENT = 'PUT_EVENT';
export const GET_EDITABLE_EVENT = 'GET_EDITABLE_EVENT';